In [1]:
import cv2
import numpy as np

In [5]:
def function(img):
    height,width,channels = img.shape
    emptyImage=np.zeros((800,800,channels),np.uint8)
    sh=800/height
    sw=800/width
    for i in range(800):
        for j in range(800):
            x=int(i/sh+0.5)
            y=int(j/sw+0.5)
            emptyImage[i,j]=img[x,y]
    return emptyImage

In [6]:
img=cv2.imread("lenna.png")

In [7]:
zoom=function(img)

In [8]:
print(zoom)

[[[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [125 137 226]
  ...
  [110 130 221]
  [ 90  99 200]
  [ 90  99 200]]

 ...

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 57  22  82]
  ...
  [ 81  71 181]
  [ 81  74 185]
  [ 81  74 185]]]


In [9]:
print(zoom.shape)

(800, 800, 3)


In [10]:
cv2.imshow("nearest interp",zoom)
cv2.imshow("image",img)
cv2.waitKey(0)

-1