In [18]:
import numpy as np
import cv2

## 1.wrap Matrix

In [21]:
def WarpPerspectiveMatrix(src, dst):
    assert src.shape[0] == dst.shape[0] and src.shape[0] >= 4
    
    nums = src.shape[0]
    A = np.zeros((2*nums,8))
    B = np.zeros((2*nums,1))
    for i in range(0,nums):
        A_i = src[i,:]
        B_i = dst[i,:]
        A[2*i, :] = [A_i[0], A_i[1], 1, 0, 0, 0,
                     -A_i[0]*B_i[0], -A_i[1]*B_i[0]]
        B[2*i] = B_i[0]
        A[2*i+1, :] = [0, 0, 0, A_i[0], A_i[1], 1,
                       -A_i[0]*B_i[1], -A_i[1]*B_i[1]]
        B[2*i+1] = B_i[1]
        
    A = np.mat(A)
    warpMatrix = A.I * B # 求参数矩阵
    warpMatrix = np.array(warpMatrix).T[0]
    warpMatrix = np.insert(warpMatrix, warpMatrix.shape[0], values=1.0, axis=0) #插入a_33 = 1
    warpMatrix = warpMatrix.reshape((3, 3))
    return warpMatrix

In [2]:
src = [[10.0, 457.0],
       [395.0, 291.0],
       [624.0, 291.0],
       [1000.0, 457.0]]
src = np.array(src)
    
dst = [[46.0, 920.0],
       [46.0, 100.0],
       [600.0, 100.0],
       [600.0, 920.0]]
dst = np.array(dst)

In [22]:
warpMatrix = WarpPerspectiveMatrix(src, dst)
print(warpMatrix)

[[-5.01338334e-01 -1.35357643e+00  5.82386716e+02]
 [-1.04194431e-15 -4.84035391e+00  1.38781980e+03]
 [ 0.00000000e+00 -4.14856327e-03  1.00000000e+00]]


## 2.Perspective Transform

In [23]:
img = cv2.imread('lenna.png')

result3 = img.copy()

In [24]:
src = np.float32([[207, 151], 
                  [517, 285], 
                  [17, 601], 
                  [343, 731]])
dst = np.float32([[0, 0], 
                  [337, 0], 
                  [0, 488], 
                  [337, 488]])
print(img.shape)
# 生成透视变换矩阵；进行透视变换
m = cv2.getPerspectiveTransform(src, dst)
print("warpMatrix:")
print(m)

(512, 512, 3)
warpMatrix:
[[ 8.92263779e-01  3.76733596e-01 -2.41585375e+02]
 [-4.08140258e-01  9.44205073e-01 -5.80899328e+01]
 [-8.53836442e-05  5.16464182e-05  1.00000000e+00]]


In [25]:
result = cv2.warpPerspective(result3, m, (337, 488))
cv2.imshow("src", img)
cv2.imshow("result", result)
cv2.waitKey(0)

-1